services:
  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.8.1'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 5
    network_mode: "host"
  spring-elastic:
    container_name: spring-elastic
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-elastic:latest
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    network_mode: "host"
