services:
  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
    networks:
      - spring-network
  spring-elastic:
    container_name: spring-elastic
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-elastic:latest
    ports:
      - "8080:8080"
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge